language: rust
sudo: false
dist: xenial

cache:
  cargo: true
  apt: true

matrix:
  include:
    - rust: stable
    - rust: nightly
  allow_failures:
    - rust: stable

before_script:
  - |
    export PATH=$PATH:~/.cargo/bin
    sudo apt-get install -y libsdl2-dev
    rustup component add rustfmt-preview

script:
  - |
    cargo fmt --all -- --check
    cargo clean
    cargo test -- --nocapture
