[package]
name = "nes-derives"
version = "0.1.0"
authors = ["Josh Leeb-du Toit <josh.leebdutoit@gmail.com>"]

[dependencies]
heck = "0.3.0"
proc-macro2 = "0.4.8"
quote = "0.6.3"
syn = "0.14.4"

[lib]
proc-macro = true
